packages:
    - 'cashtab'
    - 'apps/**/*'
    - 'web/*'
    - 'modules/**/*'
overrides:
    '@vercel/fun>tar@<7.5.11': '>=7.5.15'
    '@vercel/node>undici@<6.24.0': '>=6.25.0'
    '@vercel/python-analysis>minimatch@<10.2.3': '>=10.2.5'
    '@vercel/backends>path-to-regexp@<8.4.0': '>=8.4.2'
    '@vercel/fun>path-to-regexp@<8.4.0': '>=8.4.2'
    '@vercel/express>path-to-regexp@<8.4.0': '>=8.4.2'
    '@vercel/hono>path-to-regexp@<8.4.0': '>=8.4.2'
    '@vercel/static-config>ajv@<8.18.0': '>=8.20.0'
    '@vercel/backends>srvx@<0.11.3': '>=0.11.15'
    'vercel>smol-toml@<1.6.1': '>=1.6.1'
    '@vercel/python-analysis>smol-toml@<1.6.1': '>=1.6.1'
    '@vercel/rust>smol-toml@<1.6.1': '>=1.6.1'
