#!/usr/bin/env python3
# create a BIP70 payment request signed with a certificate

# Note that the tlslite package has not been updated since 2015, and no longer works
# with recent python versions.
# tlslite-ng is a drop-in replacement (`pip install tlslite-ng`)
import tlslite

from electrumabc import paymentrequest
from electrumabc import paymentrequest_pb2 as pb2
from electrumabc.address import Address
from electrumabc.transaction import Transaction

chain_file = "mychain.pem"
cert_file = "mycert.pem"
amount = 1000000
address = Address.from_string("18U5kpCAU4s8weFF8Ps5n8HAfpdUjDVF64")
memo = "blah"
out_file = "payreq"


with open(chain_file, "r") as f:
    chain = tlslite.X509CertChain()
    chain.parsePemList(f.read())

certificates = pb2.X509Certificates()
certificates.certificate.extend(map(lambda x: str(x.bytes), chain.x509List))

with open(cert_file, "r") as f:
    rsakey = tlslite.utils.python_rsakey.Python_RSAKey.parsePEM(f.read())

pr_string = paymentrequest.make_payment_request(amount, address.to_script(), memo, rsakey)

with open(out_file, "wb") as f:
    f.write(pr_string)

print("Payment request was written to file '%s'" % out_file)
