FROM ubuntu:18.04@sha256:2aeed98f2fa91c365730dc5d70d18e95e8d53ad4f1bbf4269c3bb625060383f0

ARG UBUNTU_MIRROR=http://archive.ubuntu.com/ubuntu/

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN echo deb ${UBUNTU_MIRROR} bionic main restricted universe multiverse > /etc/apt/sources.list && \
    echo deb ${UBUNTU_MIRROR} bionic-updates main restricted universe multiverse >> /etc/apt/sources.list && \
    echo deb ${UBUNTU_MIRROR} bionic-backports main restricted universe multiverse >> /etc/apt/sources.list && \
    echo deb ${UBUNTU_MIRROR} bionic-security main restricted universe multiverse >> /etc/apt/sources.list && \
    apt-get update -q && \
    apt-get install -qy \
        git=1:2.17.1-1ubuntu0.18 \
        wget=1.19.4-1ubuntu2.2 \
        make=4.1-9.1ubuntu1 \
        autotools-dev=20180224.1 \
        autoconf=2.69-11 \
        libtool=2.4.6-2 \
        xz-utils=5.2.2-1.3 \
        libffi-dev=3.2.1-8 \
        libncurses5-dev=6.1-1ubuntu1.18.04.1 \
        libsqlite3-dev=3.22.0-1ubuntu0.7 \
        libusb-1.0-0-dev=2:1.0.21-2 \
        libudev-dev=237-3ubuntu10.57 \
        gettext=0.19.8.1-6ubuntu0.3 \
        pkg-config=0.29.1-0ubuntu2 \
        libdbus-1-3=1.12.2-1ubuntu1.4 \
        libpcsclite-dev=1.8.23-1 \
        swig=3.0.12-1 \
        libxkbcommon-x11-0=0.8.2-1~ubuntu18.04.1 \
        libxcb1=1.13-2~ubuntu18.04 \
        libxcb-icccm4=0.4.1-1ubuntu1 \
        libxcb-image0=0.4.0-1build1 \
        libxcb-keysyms1=0.4.0-1 \
        libxcb-randr0=1.13-2~ubuntu18.04 \
        libxcb-render-util0=0.3.9-1 \
        libxcb-render0=1.13-2~ubuntu18.04 \
        libxcb-shape0=1.13-2~ubuntu18.04 \
        libxcb-shm0=1.13-2~ubuntu18.04 \
        libxcb-sync1=1.13-2~ubuntu18.04 \
        libxcb-util1=0.4.0-0ubuntu3 \
        libxcb-xfixes0=1.13-2~ubuntu18.04 \
        libxcb-xinerama0=1.13-2~ubuntu18.04 \
        libxcb-xkb1=1.13-2~ubuntu18.04 \
        libx11-xcb1=2:1.6.4-3ubuntu0.4 \
        autopoint=0.19.8.1-6ubuntu0.3 \
        zlib1g-dev=1:1.2.11.dfsg-0ubuntu2 \
        libfreetype6=2.8.1-2ubuntu2.2 \
        libfontconfig1=2.12.6-0ubuntu2 \
        libssl-dev=1.1.1-1ubuntu2.1~18.04.23 \
        rustc=1.65.0+dfsg0ubuntu1~llvm2-0ubuntu0.18.04 \
        cargo=0.66.0+ds0ubuntu0.libgit2-0ubuntu0.18.04 \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean

# create new user to avoid using root; but with sudo access and no password for convenience.
ENV USER="user"
ENV HOME_DIR="/home/${USER}"
ENV WORK_DIR="${HOME_DIR}/wspace" \
    PATH="${HOME_DIR}/.local/bin:${PATH}"
RUN useradd --create-home --shell /bin/bash ${USER}
RUN usermod -append --groups sudo ${USER}
RUN echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
WORKDIR ${WORK_DIR}
RUN chown --recursive ${USER} ${WORK_DIR}
USER ${USER}
