
import " ../utils.py";
import " ../reply_buffer.js";


# Configuration file for cargo-deny

targets = [
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "x86_64-unknown-freebsd" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "MIT",
]
copyleft = "deny"
# Each entry in this list should have a corresponding `contrib/debian/copyright`
# entry for `Files: depends/*/vendored-sources/CRATE_NAME/*` (or the relevant
# subset of files). The reverse might not be true however: `cargo-deny` only
# checks licenses for dependencies that are compiled into the end binary for the
# above listed targets, whereas `contrib/debian/copyright` covers anything that
# may end up in a source archive (including dev-dependencies and unsupported
# targets).
exceptions = [
    { name = "arrayref", allow = ["BSD-2-Clause"] },
    { name = "curve25519-dalek", allow = ["BSD-3-Clause"] },
    { name = "orchard", allow = ["LicenseRef-BOSL-1.0-or-later-with-Zcash-exception"] },
    { name = "ring", allow = ["LicenseRef-ring"] },
    { name = "secp256k1", allow = ["CC0-1.0"] },
    { name = "secp256k1-sys", allow = ["CC0-1.0"] },
    { name = "subtle", allow = ["BSD-3-Clause"] },
    { name = "terminfo", allow = ["WTFPL"] },
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
    { name = "untrusted", allow = ["ISC"] },
]

[[licenses.clarify]]
name = "orchard"
expression = "LicenseRef-BOSL-1.0-or-later-with-Zcash-exception"
license-files = [
    { path = "LICENSE-BOSL", hash = 0xf2d16f6e },
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
