<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AutoPEP8FormatLinter' => 'linter/AutoPEP8Linter.php',
    'CheckDocLinter' => 'linter/CheckDocLinter.php',
    'ClangFormatLinter' => 'linter/ClangFormatLinter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AutoPEP8FormatLinter' => 'ArcanistExternalLinter',
    'CheckDocLinter' => 'ArcanistExternalLinter',
    'ClangFormatLinter' => 'ArcanistExternalLinter',
  ),
));
