<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AssertWithSideEffectsLinter' => 'linter/AssertWithSideEffectsLinter.php',
    'AutoPEP8FormatLinter' => 'linter/AutoPEP8Linter.php',
    'CHeaderLinter' => 'linter/CHeaderLinter.php',
    'CheckDocLinter' => 'linter/CheckDocLinter.php',
    'ClangFormatLinter' => 'linter/ClangFormatLinter.php',
    'FormatStringLinter' => 'linter/FormatStringLinter.php',
    'IncludeGuardLinter' => 'linter/IncludeGuardLinter.php',
    'IncludeQuotesLinter' => 'linter/IncludeQuotesLinter.php',
    'IncludeSourceLinter' => 'linter/IncludeSourceLinter.php',
    'LocaleDependenceLinter' => 'linter/LocaleDependenceLinter.php',
    'PythonFormatLinter' => 'linter/PythonFormatLinter.php',
    'TestsLinter' => 'linter/TestsLinter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AssertWithSideEffectsLinter' => 'ArcanistLinter',
    'AutoPEP8FormatLinter' => 'ArcanistExternalLinter',
    'CHeaderLinter' => 'ArcanistLinter',
    'CheckDocLinter' => 'ArcanistExternalLinter',
    'ClangFormatLinter' => 'ArcanistExternalLinter',
    'FormatStringLinter' => 'ArcanistExternalLinter',
    'IncludeGuardLinter' => 'ArcanistLinter',
    'IncludeQuotesLinter' => 'ArcanistLinter',
    'IncludeSourceLinter' => 'ArcanistLinter',
    'LocaleDependenceLinter' => 'ArcanistLinter',
    'PythonFormatLinter' => 'ArcanistExternalLinter',
    'TestsLinter' => 'ArcanistExternalLinter',
  ),
));
