#!/usr/bin/env bash
export LC_ALL=C
set -e -o pipefail

# Source the common prelude to check that we're at the top directory of the Bitcoin ABC repository
# shellcheck source=libexec/prelude.bash
source "$(dirname "${BASH_SOURCE[0]}")/libexec/prelude.bash"

git clean -xdff \
 --exclude=depends/sources \
 --exclude=depends/built \
 --exclude=depends/SDKs
