#!/bin/sh
### BEGIN INIT INFO
# Provides:          TeamCity Build Agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start build agent daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
#Provide the correct user name:
USER="teamcity"
AGENT_PATH="~/buildAgent/bin"

case "$1" in
start)
 su - $USER -c "cd ${AGENT_PATH} ; ./agent.sh start"
;;
stop)
 su - $USER -c "cd ${AGENT_PATH} ; ./agent.sh stop"
;;
status)
 su - $USER -c "cd ${AGENT_PATH} ; ./agent.sh status"
;;
*)
  echo "usage start/stop"
  exit 1
 ;;

esac

exit 0
