#!/bin/bash

wd=`pwd`

# Default host IP is 10.0.2.2
if [ -z "$GITIAN_HOST_IP" ]; then
  GITIAN_HOST_IP=10.0.2.2
fi

# Default to host IP if the MIRROR_HOST is not set, or set to 127.0.0.1
if [ -z "$MIRROR_HOST" ] || [ "$MIRROR_HOST" == "127.0.0.1" ]; then
  MIRROR_HOST=$GITIAN_HOST_IP
fi

sed "s;HOSTIP;$MIRROR_HOST;g" < target-bin/bootstrap-fixup.in > target-bin/bootstrap-fixup
