name: C/C++ CI

on:Skip to content

You have unread notifications

Code

Pull requests

Actions

Projects

Security

Insights

Settings

Notification settings

Fork your own copy of Qoutip/bitcoin-abc

Unstar this repository

Bitcoin ABC develops node software and infrastructure for the eCash project. This a mirror of the official Bitcoin-ABC repository. Please see README.md

reviews.bitcoinabc.org

License

 MIT license

 1 star

 705 forks

 0 watching

 Activity

Public repository · Forked from Bitcoin-ABC/bitcoin-abc

Qoutip/bitcoin-abc

 Branches

 Tags

This branch is 4 commits ahead, 3 commits behind Bitcoin-ABC:master.

Latest commit

@Qoutip

Qoutip

…

22 minutes ago

Git stats

Files

README.md

Bitcoin ABC Logo

The goal of Bitcoin ABC is to create sound money that is usable by everyone in the world. This is a civilization-changing technology which will dramatically increase human flourishing, freedom, and prosperity. The project aims to achieve this goal by implementing a series of optimizations and protocol upgrades that will enable peer-to-peer digital cash to succeed at mankind scale.

What is eCash?

eCash is a digital currency that enables instant payments to anyone, anywhere in the world. It uses peer-to-peer technology to operate with no central authority: managing transactions and issuing money are carried out collectively by the network. eCash is a descendant of Bitcoin.

What is Bitcoin ABC?

Bitcoin ABC is the name of open-source software which enables the use of eCash. It is a fork of the Bitcoin Core software project.

License

Bitcoin ABC is released under the terms of the MIT license. See COPYING for more information or see https://opensource.org/licenses/MIT.

Development Process

This Github repository contains only source code of releases.

Bitcoin ABC development takes place at reviews.bitcoinabc.org

If you would like to contribute, please read CONTRIBUTING.

Disclosure Policy

See DISCLOSURE_POLICY

Releases

No releases published

Create a new release

Packages

No packages published

Publish your first package

Languages

C++

37.2%

 

Python

28.2%

 

JavaScript

23.6%

 

C

4.4%

 

Rust

1.8%

 

Shell

1.0%

 

Other

3.8%

Qoutip/bitcoin-abc: Bitcoin ABC develops node software and infrastructure for the eCash project. This a mirror of the official Bitcoin-ABC repository. Please see README.md
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
